#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI-RPI2

on:
  schedule:
    - cron: 0 19 * * *
  push:
    branches: 
      - master

env:
  DEVICE: bcm27xx
  DEVICE_SUB: bcm2709
  CONFIGFILE_NAME: rpi2.config.seed
  BITBUCKET_USER: muyeyifeng
  BITBUCKET_EMAIL: muyeyifeng@bitbucket.org
  BITBUCKET_NAME: docker-rpi2-def
  BITBUCKET_URL: muyeyifeng@bitbucket.org:muyeyifeng/docker-rpi2-def.git
  DOCKERFILE: rpi2-Dockerfile
  SSH_KEY: bitbucket.pem
  ROOTFS_FILE_NAME: openwrt-bcm27xx-bcm2709-rpi-2-rootfs.tar.gz
  EXT4_FACTORY_NAME: openwrt-bcm27xx-bcm2709-rpi-2-ext4-factory.img.gz
  EXT4_SYSUPGRADE_NAME: openwrt-bcm27xx-bcm2709-rpi-2-ext4-sysupgrade.img.gz

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 1000000

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # 利用挂载在 /mnt/ 的 14G 额外空间:
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Add SSH-key&Clone source code
        run: |
         eval `ssh-agent`
         chmod 600 $SSH_KEY
         ssh-add $SSH_KEY
         mkdir -p ~/.ssh/
         ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
         ssh -T $BITBUCKET_EMAIL
         git clone  $BITBUCKET_URL
         git clone  https://github.com/coolsnowwolf/lede

      - name: Update feeds
        run: |
          echo "======================="
          echo "Docker"
          echo "======================="
          ls $BITBUCKET_NAME
          echo "======================="
          echo "======================="
          echo "Lede"
          echo "======================="
          ls lede
          echo "======================="
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          cp $CONFIGFILE_NAME lede/defconfig
          cd lede
          ls
          cat defconfig >> .config
          make defconfig
          cat .config

      - name: Make download
        run: |
          ls
          cd lede
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          ls
          cd lede
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare to push
        run: |
          rm -rf ./$BITBUCKET_NAME/*
          echo "======================="
          ls ./$BITBUCKET_NAME/
          echo "======================="
          cp ./lede/bin/targets/$DEVICE/$DEVICE_SUB/$ROOTFS_FILE_NAME ./$BITBUCKET_NAME/
          cp ./$DOCKERFILE ./$BITBUCKET_NAME/Dockerfile
          cp ./README.md ./$BITBUCKET_NAME/README.md
          ls ./$BITBUCKET_NAME/
          echo "======================="

      - name: Push bitbucket
        run: |
         eval `ssh-agent`
         chmod 600 $SSH_KEY
         ssh-add $SSH_KEY
         mkdir -p ~/.ssh/
         ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
         ssh -T $BITBUCKET_EMAIL
         cd $BITBUCKET_NAME
         git config --global user.email '$BITBUCKET_EMAIL'
         git config --global user.name '$BITBUCKET_USER'
         git add .
         git commit -m "Build by github actions"
         git push  $BITBUCKET_URL


#      - name: Prepare artifact
#        run: |
#          find ./lede/bin/targets/ -type d -name "packages" | xargs rm -rf {}
#          mkdir targets
#          mv ./lede/bin/targets/$DEVICE/$DEVICE_SUB/$EXT4_FACTORY_NAME ./targets
#          mv ./lede/bin/targets/$DEVICE/$DEVICE_SUB/$EXT4_SYSUPGRADE_NAME ./targets

#      - name: Upload artifact
#        uses: actions/upload-artifact@master
#        with:
#          name: OPENWRT-EXT4-FACTORY-SYSUPGRADE
#          path: ./targets/
